### ISSUE TITLE
Requirements.txt problems

### ISSUE THREAD

**Issue by mweinelt** [jesopo/ircrobots#3]
- Don't pin specific versions, it makes packaging very hard.
- Dataclasses is built-in from Python 3.7 and therefore needs to be conditional
  `dataclasses; python_version < "3.7"`
- anyio has reached version 2.0, may be a breaking change, the tests don't go there

**Comment by mweinelt** [comment]
Still something I need to patch downstream.

Check out this reference https://python-poetry.org/docs/versions/, it might be more convenient to switch to poetry and use that.

**Comment by jesopo** [comment]
how's it looking now

**Comment by mweinelt** [comment]
Yep, that let's me drop all but one override. Anyio has been past 2.0 for a few months, we're currently tracking 2.0.2, but that coudl certainly have breaking changes. PTAL. https://github.com/agronholm/anyio.

ERROR: Could not find a version that satisfies the requirement anyio~=1.3.0 (from ircrobots==0.3.6) (from versions: none)

**Comment by jesopo** [comment]
why is it failing to satisfy that requirement if it's still available on pypi

**Comment by mweinelt** [comment]
Because we're not pulling packages from PyPi on an ad hoc basis. They're neatly packaged in our downstream package set.

**Comment by jesopo** [comment]
jesopo/ircrobots@69e303dfa918c8fc4d2e75af10e3dda871d82dd8 😎
